AY2122S2-CS2103T-W13-3/tp

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/tag/Skill.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/storage/JsonAdaptedSkill.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
=> Add skeleton of Skill field

docs/UserGuide.md
Update AB3 features description to that of HackNet,
changing address field to github username field.
=> Migrate user guide to HackNet

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Add functionality to edit `skill`
Fix some testcases in edit skill and address book
=> Add edit skill functionality and fix testCase

docs/UserGuide.md
Documentation to update user guide to include skill feature.
=> Update userguide to include the skill feature

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FilterSkillCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/PersonBySkillProficiencyComparator.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/FilterSkillCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/commands/SortCommandTest.java, src/test/java/seedu/address/logic/parser/SortCommandParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/person/PersonBySkillProficiencyComparatorTest.java, src/test/java/seedu/address/testutil/TestUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Add a new feature to allow users of **HackNet** to sort their contacts by proficiency of skill level.
Fixes: AY2122S2-CS2103T-W13-3/tp#23
=> Add sort command

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/person/GithubUsername.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/model/person/GithubUsernameTest.java
Change GitHub username field in GUI to be a clickable hyperlink linking to the contact's GitHub profile
=> Update GitHub username field in HackNet

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/FilterPastTeamCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java
Add a new feature to allow users of **HackNet** to list past teammates.
UG has been updated as well.
=> Add filterteam command

src/main/resources/view/DarkTheme.css, src/test/java/seedu/address/model/team/SkillTest.java
change UI for `skill`
Add test case for `skill` class
To make HackNet more visually appealing
To improve test coverage
=> Change UI for skillSet and add testcases

docs/UserGuide.md, src/main/java/seedu/address/ui/PersonCard.java
Minor formatting changes
Removed unused method in `PersonCard`
New PR as previous PR https://github.com/AY2122S2-CS2103T-W13-3/tp/pull/66 failed to start CI
=> Minor formatting changes to UG

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java
Usage Msg for `AddCommand` and `EditCommand`  is outdated. The outdated message gets printed out in the response box when the user gets the command syntax wrong
=> Branch update command usage

docs/UserGuide.md
=> Add alternate way to start application in UG

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/FilterPastTeamCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ShowCommand.java, src/main/java/seedu/address/model/team/Skill.java, src/main/java/seedu/address/model/team/SkillSet.java, src/test/java/seedu/address/model/person/PersonContainsSkillPredicateTest.java, src/test/java/seedu/address/model/team/SkillSetTest.java, src/test/java/seedu/address/model/team/SkillTest.java, src/test/java/seedu/address/testutil/TypicalSkills.java
Bug fixes for 
- Minor UG details
- Duplicate skill when using edit with different skill proficiency
- Skill input validation to exclude 0 
- HelpCommand to support the use of commands such as `undo`
Refer to Issue https://github.com/AY2122S2-CS2103T-W13-3/tp/issues/139 for list of issues this PR addresses
=> Bug fix for duplicate skill issue and include more support for `HelpCommand`

docs/UserGuide.md
Updates UG for the following documentation issues:
* #124
* #103 
* #121 
* #101
=> Update UG for #103, #121, #124, #101

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/EditCommand.java
The incorrect argument formats have been fixed including edit and add
command. The errors in command format summary table has also been
corrected.
=> Improve UG in various aspects

src/main/java/seedu/address/logic/commands/AddCommand.java
Help msg from using help comand does not reflect the changes in add command
=> Fix help msg to give correct example for use of Add command

src/main/java/seedu/address/logic/commands/EditCommand.java
User will better understand the usage guide that is displayed when
he/she has entered an invalid command format.
=> Improve usage msg of edit command

src/main/java/seedu/address/model/person/GithubUsername.java, src/test/java/seedu/address/model/person/GithubUsernameTest.java
Fix Issue https://github.com/AY2122S2-CS2103T-W13-3/tp/issues/132
Add checks for 
- consecutive hyphens
- start/end characters for hyphens
- length of username
=> Bug fix for Github username

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java
Usage msg of add and edit command was improved as well
=> Improve UG to denote how HackNet treats whitspaces

src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/storage/UserInputHistoryTest.java
Added testcases for `UserInputHistory` and removed unused methods for parsing and editing `skill` and `team`
=> Add testcases to improve coverage and removed unused methods

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/model/person/PersonTest.java
Addresses https://github.com/AY2122S2-CS2103T-W13-3/tp/issues/129 and https://github.com/AY2122S2-CS2103T-W13-3/tp/issues/116
Allows duplicate name fields but rejects **any** duplicate field in
- github username
- phone number
- email
Since people cannot share the above contact information but some people might have the same names.
=> Fix HackNet duplicate fields issue

src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/FilterPastTeamCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/model/person/GithubUsernameTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/team/SkillSetTest.java, src/test/java/seedu/address/testutil/TypicalSkills.java
Added Unit Tests for:
1. `FilterPastTeamCommand`
2. `HelpCommand`
3. `Person`
4. `UniquePersonsList`
5. `GithubUsername`
6. `SkillSet`
Added Loggers for:
1. `UndoCommand`
2. `RedoCommand`
=> Add tests to improve coverage

docs/DeveloperGuide.md
=> Change links of DG to direct to W13-3 instead of address book

docs/DeveloperGuide.md, docs/index.md
update index from address book to HackNet
add line break to DG for pdf conversion
=> update index and add line breaks to DG
